Added llvmlib-C library build, manually pulled some fixes from conda-forge's 17.x branch, updated build and install scripts, added libffi and libxml2 for all platforms, pinned consistently, pulled in update from llvmdev19, renamed patches.
Signed-off-by: scott hain <shain@anaconda.com>

diff --git a/recipe/meta.yaml b/recipe/meta.yaml
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,26 +1,30 @@
 {% set version = "17.0.6" %}
 {% set major_ver = version.split(".")[0] %}
 
+# as of LLVM 17, we expect an "rc" suffix for the release candidates
+{% set extra = "rc" if version.split(".")[-1] not in "01234567" else "" %}
+{% set extra = "git" if version.split(".")[-1] == "dev0" else extra %}
+
 package:
   name: llvm-package
   version: {{ version }}
 
 source:
-  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
-  sha256: 58a8818c60e6627064f312dbf46c02d9949956558340938b71cf731ad8bc0813
+  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
+  sha256: 81494d32e6f12ea6f73d6d25424dbd2364646011bb8f7e345ca870750aa27de1
   patches:
+    - patches/0001-pass-through-QEMU_LD_PREFIX-SDKROOT.patch
     - patches/0002-restore-macos-10.9-support.patch
+    # this patch adds the needed version numbers to 
+    - patches/0003-change-osx-version-for-libllvm-c.patch
     # These two patches remove expected test failures.
     - patches/0004-remove-unsupported-intrinsic-test.patch
     - patches/0005-remove-permission-based-unit-tests.patch
-    # This patches cmake code which isn't hit in the current configuration, however it's kept in case we want to build
-    # libllvm-c in the future
-    - patches/osx_ver.patch
     # A different approach to this fix: https://github.com/conda-forge/llvmdev-feedstock/commit/1da42e54b055d26bc58da77bd1f88ad460ac90f4
-    - patches/MSVC_DIA_SDK_path_fix.diff  # [win]
+    # - patches/MSVC_DIA_SDK_path_fix.diff  # [win]
 
 build:
-  number: 1
+  number: 3
   merge_build_host: false
 
 requirements:
@@ -28,23 +32,23 @@ requirements:
     - {{ compiler('cxx') }}
     - cmake
     - ninja
-    - python >=3
+    - python
     - libcxx {{ cxx_compiler_version }}  # [osx]
     - patch       # [not win]
     - m2-patch    # [win]
-    - git         # [(linux and x86_64)]
+    - git
   host:
     - libcxx {{ cxx_compiler_version }}  # [osx]
-    - libffi {{ libffi }}   # [unix]
-    # libxml2 supports a windows-only feature, see https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/llvm/include/llvm/WindowsManifest/WindowsManifestMerger.h
-    - libxml2 {{ libxml2 }}  # [win]
+    - backtrace                          # [unix]
+    - libffi {{ libffi }}
+    - libxml2 {{ libxml2 }}
     - zlib {{ zlib }}
     - zstd {{ zstd }}
 
 outputs:
   # Contains everything
   - name: llvmdev
-    script: install_llvm.sh  # [not win]
+    script: install_llvm.sh   # [unix]
     script: install_llvm.bat  # [win]
     build:
       skip: true  # [(win and vc<14)]
@@ -55,20 +59,30 @@ outputs:
         - {{ compiler('cxx') }}
         - cmake
         - ninja
-        - python >=3
+        - python
+        - libcxx {{ cxx_compiler_version }}  # [osx]
       host:
-        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
+        - libcxx {{ cxx_compiler_version }}  # [osx]
+        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
         - {{ pin_subpackage("llvm-tools", exact=True) }}
-        - libxml2 {{ libxml2 }}  # [win]
+        - libffi {{ libffi }}
+        - libxml2 {{ libxml2 }}
         - zlib {{ zlib }}
         - zstd {{ zstd }}
       run:
-        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
+        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
         - {{ pin_subpackage("llvm-tools", exact=True) }}
-        - libcxx >={{ cxx_compiler_version }}  # [osx]
+        - libcxx >={{ cxx_compiler_version }}                           # [osx]
+      run_constrained:
+        - llvm        {{ version }}
+        - llvm-tools  {{ version }}
+        - clang       {{ version }}
+        - clang-tools {{ version }}
     test:
+      requires:
+        - ripgrep  # [win]
       commands:
-        - $PREFIX/bin/llvm-config --libs                                 # [not win]
+        - $PREFIX/bin/llvm-config --libs                                # [not win]
         - test -f $PREFIX/include/llvm/Pass.h                           # [not win]
         - test -f $PREFIX/lib/libLLVMCore.a                             # [not win]
         - $PREFIX/libexec/llvm/not false                                # [not win]
@@ -77,62 +91,78 @@ outputs:
         - if not exist "%LIBRARY_PREFIX%"\\libexec\llvm\not.exe exit 1  # [win]
         - if not exist "%LIBRARY_BIN%"\\llvm-nm.exe exit 1              # [win]
         - llvm-nm.exe --help                                            # [win]
+        # ensure we've correctly inserted %VSINSTALLDIR% into the CMake metadata for LLVM;
+        # we're looking for: `INTERFACE_LINK_LIBRARIES "$ENV{VSINSTALLDIR}/DIA SDK/lib/amd64/diaguids.lib;[...]`instead
+        - rg -e "INTERFACE_LINK_LIBRARIES\s\"\$ENV\{VSINSTALLDIR\}[/\w\s]+/diaguids\.lib" %LIBRARY_LIB%\cmake\llvm\LLVMExports.cmake  # [win]
 
   # Contains the shared libraries. To make different LLVM libraries co-installable
   # soversion is appended to the package name.
   - name: libllvm{{ major_ver }}
     script: install_llvm.sh  # [not win]
     build:
+      activate_in_script: true
       skip: true  # [win and vc<14]
-      run_exports:   # [not win]
-        - {{ pin_subpackage("libllvm" + major_ver, max_pin="x.x") }}  # [not win]
+      run_exports:                                                    # [not win]
+        - {{ pin_subpackage("libllvm" ~ major_ver, max_pin="x.x") }}  # [not win]
       missing_dso_whitelist:  # [s390x]
         - $RPATH/ld64.so.1    # [s390x]
     requirements:
       build:
         - {{ compiler('cxx') }}
-        - ninja                  # [not win]
-        - cmake                  # [not win]
-        - python >=3             # [not win]
+        - ninja                    # [not win]
+        - cmake                    # [not win]
+        - python                   # [not win]
       host:
         - libcxx {{ cxx_compiler_version }}  # [osx]
-        - libffi {{ libffi }}  # [unix]
-        - libxml2 {{ libxml2 }}  # [win]
+        - libxml2                 # [unix or win]
+        - libffi {{ libffi }}
+        - libxml2 {{ libxml2 }}
         - zlib {{ zlib }}
         - zstd {{ zstd }}
       run:
+        # we need to do this manually because clang_bootstrap has no run-export
         - libcxx >={{ cxx_compiler_version }}  # [osx]
         - {{ pin_compatible('libffi', max_pin='x.x') }}  # [unix]
-        - zlib    # [osx]
+        - zlib {{ zlib }}    # [osx]
     test:
       commands:
-        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}${SHLIB_EXT}  # [not win]
+        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.so     # [linux]
+        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.dylib  # [osx]
+        - if not exist %LIBRARY_BIN%\LLVM-C.dll exit 1                  # [win]
+        - if not exist %LIBRARY_LIB%\LLVM-C.lib exit 1                  # [win]
+        # Make sure libffi was linked
+        - otool -L $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.dylib | grep -i ffi  # [osx]
+        - ldd $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.so | grep -i ffi          # [linux]
 
   # This is a meta package so that people can use the latest libllvm and also
   # for run_exports
   - name: llvm
     build:
       skip: true  # [(win and vc<14)]
-      run_exports:   # [not win]
-        - {{ pin_subpackage("libllvm" + major_ver, max_pin="x.x") }}  # [not win]
+      run_exports:                                                    # [not win]
+        - {{ pin_subpackage("libllvm" ~ major_ver, max_pin="x.x") }}  # [not win]
     requirements:
       build:
       host:
-        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}  # [not win]
-        - libxml2 {{ libxml2 }}  # [win]
+        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}     # [not win]
+        - libxml2 {{ libxml2 }}
+        - libffi {{ libffi }}
         - zlib {{ zlib }}
         - zstd {{ zstd }}
-      run:   # [not win]
-        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}  # [not win]
-      run_constrained:             # [not win]
-        - llvmdev   {{ version }}  # [not win]
+      run:                                                            # [not win]
+        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}     # [not win]
+      run_constrained:
+        - llvmdev     {{ version }}
+        - llvm-tools  {{ version }}
+        - clang       {{ version }}
+        - clang-tools {{ version }}
     test:
       commands:
         - echo "Hello World!"
 
   # Contains LLVM tools
   - name: llvm-tools
-    script: install_llvm.sh   # [not win]
+    script: install_llvm.sh   # [unix]
     script: install_llvm.bat  # [win]
     build:
       skip: true  # [(win and vc<14)]
@@ -143,28 +173,71 @@ outputs:
         - {{ compiler('cxx') }}
         - cmake
         - ninja
-        - python >=3
+        - python
+        - libcxx {{ cxx_compiler_version }}  # [osx]
       host:
-        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
-        - libxml2 {{ libxml2 }}  # [win]
+        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
+        - libffi {{ libffi }}
+        - libxml2 {{ libxml2 }}
         - zlib {{ zlib }}
         - zstd {{ zstd }}
         - libcxx {{ cxx_compiler_version }}  # [osx]
       run:
+        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
         - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
         - libcxx >={{ cxx_compiler_version }}  # [osx]
       run_constrained:
-        - llvmdev   {{ version }}
+        - llvm        {{ version }}
+        - llvmdev     {{ version }}
+        - clang       {{ version }}
+        - clang-tools {{ version }}
     test:
       commands:
         - $PREFIX/bin/llc -version                               # [not win]
+        # The test for windows is split into two lines instead of having it in one line
+        # like its unix variant because of a YAML parsing issue.
         - if not exist "%LIBRARY_BIN%"\\llc.exe exit 1           # [win]
         - llc -version                                           # [win]
+        - test ! -f $PREFIX/bin/llvm-config                      # [not win]
+        - if exist "%LIBRARY_BIN%"\\llvm-config.exe exit 1       # [win]
+
+  # Contains LLVM-C shared library
+  - name: libllvm-c{{ major_ver }}
+    script: install_llvm.sh   # [unix]
+    script: install_llvm.bat  # [win]
+    build:
+      run_exports:
+        - {{ pin_subpackage("libllvm-c" + major_ver, max_pin="x.x") }}
+      activate_in_script: true
+      # not supported on linux, see
+      # https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/tools/llvm-shlib/CMakeLists.txt#L82-L85
+      # osx currently fails as well, see https://github.com/llvm/llvm-project/issues/64657
+      skip: true  # [not win]
+    requirements:
+      build:
+        - {{ compiler('cxx') }}
+        - cmake
+        - ninja
+        - libcxx {{ cxx_compiler_version }}  # [osx]
+      host:
+        - libcxx {{ cxx_compiler_version }}  # [osx]
+        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
+        - libffi {{ libffi }}
+        - libxml2 {{ libxml2 }}
+        - zlib {{ zlib }}
+        - zstd {{ zstd }}
+      run_constrained:
+        - llvmdev {{ version }}
+    test:
+      commands:
+        - test -f $PREFIX/lib/libLLVM-C{{ major_ver }}{{ extra }}.so # [linux]
+        - test -f $PREFIX/lib/libLLVM-C.{{ major_ver }}.dylib       # [osx]
+        - if not exist %LIBRARY_BIN%\LLVM-C.dll exit 1              # [win]
+        - if not exist %LIBRARY_LIB%\LLVM-C.lib exit 1              # [win]
 
   - name: lit
     build:
       script: python -m pip install llvm/utils/lit --no-deps --no-build-isolation -vv
-      skip: true  # [py<30]
       entry_points:
         # upstream LLVM is inconsistent; there's one way specified in lit's setup.py...
         - lit = lit.main:main
@@ -179,12 +252,11 @@ outputs:
       run:
         - python
     test:
+      requires:
+        - python
       imports:
         - lit
-      requires:
-        - pip
       commands:
-        - pip check
         - lit -h
         - llvm-lit -h
 
@@ -204,10 +276,10 @@ extra:
   skip-lints:
     # there are false positives for these checks,
     # for some of the individual outputs.
-    - output_missing_script
     - missing_tests
     - wrong_output_script_key
   recipe-maintainers:
+    - JohanMabille
     - inducer
     - jakirkham
     - mingwandroid
@@ -217,3 +289,4 @@ extra:
     - xhochy
     - h-vetinari
     - danpetry
+  feedstock-name: llvmdev
